name: Deploy via ftp
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.ftp.snackbartio.com.br }} 
        user: ${{ secrets.snackbartio1 }}
        password: ${{ secrets.PASS }}
        localDir: "https://github.com/clauderech/snackbar"
        remoteDir: "public_html"